---
title: "Peter Dimler - Portfolio"
---

# Welcome!
This is a simple portfolio for Peter Dimler (GitHub Alias: WhiskeyYankee) to showcase a few notable projects that I have worked on:

* **ICR_Project:** In the summer of 2023 I enrolled in the [Identifying Age Related Conditions](https://www.kaggle.com/competitions/icr-identify-age-related-conditions/overview/description) code competition on Kaggle. [My submission](https://www.kaggle.com/code/whiskeyyankee/notebook06df57f4df/report?scriptVersionId=137914322) ranked in the top 16% and I prepared a report that documents my efforts and explains my findings. 

* **EDAmigo:** As part of the Reproducible Computations class I took at Texas A&M in the fall of 2023, I worked with a team to build an R package that supports the EDA process. My contributions to this project focused on numeric data transformations. The EDAmigo tab outlines how the functions I built work. 

* **Stroke Analysis:** Another notable project that I completed during my masters was an analysis of stroke severity. I analyzed roughly 10GB of data from 400 different stroke patients including medical and social history, proteomics, and genetic data in the form of SNPs. The goal of the study was to discover medically relevant details that could further the understanding of stroke severity and treatment. The data made available to me was part of a larger study that is still ongoing and as a result, while I have been permitted to share my findings, I cannot share the underlying data. 
